# Generated by Django 2.1.7 on 2019-03-13 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meme',
            name='city',
            field=models.CharField(choices=[('AUS', 'Austin'), ('SMA', 'Santa Monica'), ('DAL', 'Dallas')], default='AUS', max_length=3),
        ),
        migrations.AddField(
            model_name='meme',
            name='image_upload',
            field=models.ImageField(default='../RickRoll.jpg', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='meme',
            name='image_url',
            field=models.CharField(default='https://media.giphy.com/media/5kq0GCjHA8Rwc/giphy.gif', max_length=250),
        ),
        migrations.AlterField(
            model_name='meme',
            name='creation_date',
            field=models.DateField(verbose_name='creation date'),
        ),
    ]
