# Generated by Django 2.1.7 on 2019-03-14 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20190313_2030'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contribution_text', models.TextField(max_length=250)),
                ('contribution_date', models.DateField(verbose_name='contribution date')),
                ('contribution_image', models.ImageField(default='../RickRoll.jpg', upload_to='images/')),
            ],
        ),
        migrations.RenameField(
            model_name='meme',
            old_name='creation_date',
            new_name='date',
        ),
        migrations.AlterField(
            model_name='meme',
            name='image_url',
            field=models.CharField(max_length=250),
        ),
        migrations.AddField(
            model_name='history',
            name='meme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Meme'),
        ),
    ]
